### PR TITLE
Remove unused import

### PR DESCRIPTION
**Pull request by hsinfan1996**
This line is not used, but it causes `ImportError`.

### CODE REVIEW

**Comment by damonge** [comment]
It would be extremely, extremely good if this PR could be merged. It currently makes tests fail for any code that uses fast-pt.

**Comment by jablazek** [comment]
Ah, I didn't catch the PR until just now. We have recently moved actively development to https://github.com/jablazek/FAST-PT. Would you like to move the PR over there? Are you using FAST-PT through git or conda?

**Comment by jablazek** [comment]
We do use np.trapz for the sigma^4 terms.

**Comment by damonge** [comment]
I think the point is that this function is now called `trapezoid` in scipy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.trapezoid.html

**Comment by jablazek** [comment]
Yes, sorry. That was mainly a comment for myself - I was surprised that the trapz wasn't called, but it was because we use the np version.

**Comment by hsinfan1996** [comment]
> Ah, I didn't catch the PR until just now. We have recently moved actively development to https://github.com/jablazek/FAST-PT. Would you like to move the PR over there? Are you using FAST-PT through git or conda?

I will open a new PR there. For CCL, we install FAST-PT from the source.

**Comment by jablazek** [comment]
OK. I will merge here anyway, since some people probably still use this repo. Thanks!

**Comment by hsinfan1996** [comment]
Thank you.

**Comment by hsinfan1996** [comment]
@jablazek Actually, for CCL, we install fast-pt from pypi, so it would be very helpful to push a new version to pypi.

**Pull request merged**
